### ISSUE TITLE
Webpage refreshes itself constantly

### ISSUE THREAD

**Issue by dinnerbird** [startmc/startmc.sh#24] opened 2022-01-29 16:24 UTC
Currently running Firefox 96 and the homepage for startmc.sh refreshes itself constantly, I'd say every 30 seconds or so. 
Makes it really annoying for trying to enter data and copying the generated script.

**Comment by TheTRCG** [comment] 2022-06-20 02:34
Plus one for this, its really annoying and still there now

**Comment by tadhgboyle** [comment] 2022-07-06 04:53
https://github.com/sveltejs/kit/issues/1134
https://github.com/sveltejs/kit/issues/844

This seems to be caused by some of the issues mentioned here ^

Will look into this tomorrow, some of our deps are very badly out of date

**Comment by webcrawls** [comment] 2022-07-30 18:58
This seems to be fixed now, but re-open this issue if it occurs again

**Closed as completed by webcrawls** 2022-07-30 18:58 UTC
